<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Blue_DragonBlue.png" />
    <None Remove="Images\Blue_DragonRed.png" />
    <None Remove="Images\Cards\BlueCards\Blue_DragonBlue.png" />
    <None Remove="Images\Cards\BlueCards\ChimeraBlue.png" />
    <None Remove="Images\Cards\BlueCards\ChocoboBlue.png" />
    <None Remove="Images\Cards\BlueCards\CoeurlBlue.png" />
    <None Remove="Images\Cards\BlueCards\Demon_WallBlue.png" />
    <None Remove="Images\Cards\BlueCards\GarudaBlue.png" />
    <None Remove="Images\Cards\BlueCards\IfritBlue.png" />
    <None Remove="Images\Cards\BlueCards\LeviathanBlue.png" />
    <None Remove="Images\Cards\BlueCards\MoogleBlue.png" />
    <None Remove="Images\Cards\BlueCards\OdinBlue.png" />
    <None Remove="Images\Cards\BlueCards\ShivaBlue.png" />
    <None Remove="Images\Cards\BlueCards\ThancredBlue.png" />
    <None Remove="Images\Cards\BlueCards\TitanBlue.png" />
    <None Remove="Images\Cards\BlueCards\TonberryBlue.png" />
    <None Remove="Images\Cards\BlueCards\UltimaWeaponBlue.png" />
    <None Remove="Images\Cards\BlueCards\Y%27shtolaBlue.png" />
    <None Remove="Images\Cards\RedCards\Blue_DragonRed.png" />
    <None Remove="Images\Cards\RedCards\ChimeraRed.png" />
    <None Remove="Images\Cards\RedCards\ChocoboRed.png" />
    <None Remove="Images\Cards\RedCards\CoeurlRed.png" />
    <None Remove="Images\Cards\RedCards\Demon_WallRed.png" />
    <None Remove="Images\Cards\RedCards\GarudaRed.png" />
    <None Remove="Images\Cards\RedCards\IfritRed.png" />
    <None Remove="Images\Cards\RedCards\LeviathanRed.png" />
    <None Remove="Images\Cards\RedCards\MoogleRed.png" />
    <None Remove="Images\Cards\RedCards\OdinRed.png" />
    <None Remove="Images\Cards\RedCards\ShivaRed.png" />
    <None Remove="Images\Cards\RedCards\ThancredRed.png" />
    <None Remove="Images\Cards\RedCards\TitanRed.png" />
    <None Remove="Images\Cards\RedCards\TonberryRed.png" />
    <None Remove="Images\Cards\RedCards\UltimaWeaponRed.png" />
    <None Remove="Images\Cards\RedCards\Y%27shtolaRed.png" />
    <None Remove="Images\ChimeraBlue.png" />
    <None Remove="Images\ChimeraRed.png" />
    <None Remove="Images\chocobo.jpg" />
    <None Remove="Images\ChocoboBlue.png" />
    <None Remove="Images\ChocoboRed.png" />
    <None Remove="Images\Demon_WallBlue.png" />
    <None Remove="Images\Demon_WallRed.png" />
    <None Remove="Images\ExitButton.png" />
    <None Remove="Images\Gamebackground.png" />
    <None Remove="Images\GarudaBlue.png" />
    <None Remove="Images\GarudaRed.png" />
    <None Remove="Images\IfritBlue.png" />
    <None Remove="Images\IfritRed.png" />
    <None Remove="Images\images\ChocoboRed.png" />
    <None Remove="Images\MoogleBlue.png" />
    <None Remove="Images\MoogleRed.png" />
    <None Remove="Images\OdinBlue.png" />
    <None Remove="Images\OdinRed.png" />
    <None Remove="Images\placeholder.jpg" />
    <None Remove="Images\playbutton.png" />
    <None Remove="Images\ShivaBlue.png" />
    <None Remove="Images\ShivaRed.png" />
    <None Remove="Images\TitleScreen.png" />
    <None Remove="Images\Y%27shtolaBlue.png" />
    <None Remove="Images\Y%27shtolaRed.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Game.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Cards\BlueCards\Blue_DragonBlue.png" />
    <Resource Include="Images\Cards\BlueCards\ChimeraBlue.png" />
    <Resource Include="Images\Cards\BlueCards\ChocoboBlue.png" />
    <Resource Include="Images\Cards\BlueCards\CoeurlBlue.png" />
    <Resource Include="Images\Cards\BlueCards\Demon_WallBlue.png" />
    <Resource Include="Images\Cards\BlueCards\GarudaBlue.png" />
    <Resource Include="Images\Cards\BlueCards\IfritBlue.png" />
    <Resource Include="Images\Cards\BlueCards\LeviathanBlue.png" />
    <Resource Include="Images\Cards\BlueCards\MoogleBlue.png" />
    <Resource Include="Images\Cards\BlueCards\OdinBlue.png" />
    <Resource Include="Images\Cards\BlueCards\ShivaBlue.png" />
    <Resource Include="Images\Cards\BlueCards\ThancredBlue.png" />
    <Resource Include="Images\Cards\BlueCards\TitanBlue.png" />
    <Resource Include="Images\Cards\BlueCards\TonberryBlue.png" />
    <Resource Include="Images\Cards\BlueCards\UltimaWeaponBlue.png" />
    <Resource Include="Images\Cards\BlueCards\Y'shtolaBlue.png" />
    <Resource Include="Images\Cards\RedCards\Blue_DragonRed.png" />
    <Resource Include="Images\Cards\RedCards\ChimeraRed.png" />
    <Resource Include="Images\Cards\RedCards\ChocoboRed.png" />
    <Resource Include="Images\Cards\RedCards\CoeurlRed.png" />
    <Resource Include="Images\Cards\RedCards\Demon_WallRed.png" />
    <Resource Include="Images\Cards\RedCards\GarudaRed.png" />
    <Resource Include="Images\Cards\RedCards\IfritRed.png" />
    <Resource Include="Images\Cards\RedCards\LeviathanRed.png" />
    <Resource Include="Images\Cards\RedCards\MoogleRed.png" />
    <Resource Include="Images\Cards\RedCards\OdinRed.png" />
    <Resource Include="Images\Cards\RedCards\ShivaRed.png" />
    <Resource Include="Images\Cards\RedCards\ThancredRed.png" />
    <Resource Include="Images\Cards\RedCards\TitanRed.png" />
    <Resource Include="Images\Cards\RedCards\TonberryRed.png" />
    <Resource Include="Images\Cards\RedCards\UltimaWeaponRed.png" />
    <Resource Include="Images\Cards\RedCards\Y'shtolaRed.png" />
    <Resource Include="Images\chocobo.jpg" />
    <Resource Include="Images\ExitButton.png" />
    <Resource Include="Images\Gamebackground.png" />
    <Resource Include="Images\placeholder.jpg" />
    <Resource Include="Images\playbutton.png" />
    <Resource Include="Images\TitleScreen.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
